"""add photo to favorite_restaurants

Revision ID: 4b534739ba1c
Revises: 7b6f0f8a4d21
Create Date: 2026-05-13 22:52:06.284868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b534739ba1c'
down_revision: Union[str, None] = '7b6f0f8a4d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
